### ISSUE TITLE
Static initialization

### ISSUE THREAD

**Issue by ipostr08** [EmuraDaisuke/MemoryAllocator.KanameShiki#1]
I made an allocator wrapper class template in order to use KanameShiki as an std::vector allocator. It works fine when dynamically allocating memory during runtime but fails if used during the static initialization on the program startup. E.g.:
`inline static const std::vector<int, KanameShikiAlloc<int>> BAD_DAYS = { 20150322, 20140204 };`
in a header file under Windows 10 using MSVC 2019.

Exception thrown: read access violation.
oReserver was 0xC.

```
test.exe!KanameShiki::LocalReserver::Segment::Alloc() Line 55	C++
 	test.exe!KanameShiki::LocalReserver::Alloc(unsigned __int64 s) Line 143	C++
 	test.exe!KanameShiki::LocalCntx::ReserverAlloc(unsigned __int64 s) Line 62	C++
 	test.exe!KanameShiki::LocalReserverAlloc(unsigned __int64 s) Line 127	C++
 	test.exe!KanameShiki::LocalPool::operator new(unsigned __int64 sThis, unsigned short o, const std::nothrow_t & __formal) Line 144	C++
 	test.exe!KanameShiki::LocalCntx::NewPool(unsigned short o) Line 86	C++
 	test.exe!KanameShiki::LocalCntx::Alloc(unsigned __int64 s) Line 72	C++
 	test.exe!KanameShiki::Alloc(unsigned __int64 s) Line 150	C++
 	test.exe!kanameAlloc<std::_Container_proxy>::allocate(unsigned __int64 n) Line 15	C++
 	[External Code]	
 	test.exe!`dynamic initializer for 'NConst::VOLAT_PERIODS''() Line 81	C++
 	test.exe!_initterm(void(*)() * first, void(*)() * last) Line 22	C++
```

For comparison, tcmalloc works fine in this case.

What seems to be happening is that mapRealm array is only initialized in the GlobalReserver constructor, so the program references a nullptr when trying to allocate memory.

**Comment by EmuraDaisuke** [comment]
Thank you for the report!
And sorry for the bug.

Improve!

**Comment by EmuraDaisuke** [comment]
Fixed bug
Memory can be allocated even with static initialization
